Try to add Strategy Pattern
Blackolf931/TSP pull request #11
Opened 2021-09-07 08:15 UTC by Blackolf931

2021-09-07 12:00 UTC, nantonov requested changes

2021-09-07 12:00 UTC, nantonov commented on TSP/BLL/Models/EmployeeGetById.cs
> +    public class EmployeeGetById
Strange name

2021-09-09 19:36 UTC, Blackolf931 commented on TSP/BLL/Services/EmployeeService.cs
> +        private readonly IEnumerable<IStrategyService> listStrategy;
fix

2021-09-09 19:36 UTC, Blackolf931 commented on TSP/BLL/Services/EmployeeService.cs
> +        public async Task<EmployeeGetById> GetEmployeeByIdAsync(int id)
fix

2021-09-09 19:36 UTC, Blackolf931 commented on TSP/BLL/Services/GetAdditionalInformationAboutRetirePeople.cs
> +        bool IStrategyService.IsValidStrategy(int age)
fix

2021-09-09 19:36 UTC, Blackolf931 commented on TSP/BLL/Services/IGetAdditionalInterface.cs
> +    public interface IGetAdditionalInterface
deleted

2021-09-09 19:36 UTC, Blackolf931 commented on TSP/BLL/Services/IStrategyService.cs
> +    public interface IStrategyService
fix

2021-09-09 19:36 UTC, Blackolf931 commented on TSP/BLL/Services/StrategyService.cs
> +    class StrategyService
deleted

2021-09-09 19:38 UTC, Blackolf931 commented on TSP/DAL/Repositories/EmployeeRepository.cs
> +        //   _repositoryContext.Entry(entity).State = EntityState.Unchanged;
fix

2021-09-09 19:38 UTC, Blackolf931 commented on TSP/BLL/Models/EmployeeGetById.cs
> +    public class EmployeeGetById
deleted

2021-09-10 10:08 UTC, nantonov approved these changes

2021-09-10 10:08 UTC, nantonov commented on TSP/BLL/DI/DependencyRegistrar.cs
> +            services.AddScoped<IStrategy, GetAdditionalInformationAboutYoungPeople>();
rename pls

2021-09-10 10:58 UTC, Blackolf931 commented on TSP/BLL/DI/DependencyRegistrar.cs
> +            services.AddScoped<IStrategy, GetAdditionalInformationAboutYoungPeople>();
fix

2021-09-10 11:54 UTC, nantonov approved these changes

2021-09-10 11:55 UTC, merged