Connect to React
Blackolf931/TSP pull request #12
Opened 2021-09-09 19:38 UTC by Blackolf931

2021-09-12 15:20 UTC, nantonov requested changes
Delete react packages from WebApi.

2021-09-12 15:20 UTC, nantonov commented on TSP/TSP.API/Program.cs
> +
Get rid of this changes

2021-09-12 15:20 UTC, nantonov commented on TSP/TSP.API/AutoMapper/ApiProfile.cs
> +            CreateMap<OfficeAddViewModel, Office>().ReverseMap();
Does ReverseMap() really needed here?

2021-09-13 08:48 UTC, Blackolf931 commented on TSP/TSP.API/Program.cs
> +
fix

2021-09-13 08:48 UTC, Blackolf931 commented on TSP/TSP.API/AutoMapper/ApiProfile.cs
> +            CreateMap<OfficeAddViewModel, Office>().ReverseMap();
fix

2021-09-13 11:14 UTC, closed without merging