Feature/add generic controller
Blackolf931/TSP pull request #19
Opened 2021-09-17 14:03 UTC by Blackolf931

2021-09-17 14:11 UTC, nantonov requested changes

2021-09-17 14:11 UTC, nantonov commented on TSP/BLL/Services/EmployeeService.cs
> +                return _mapper.Map<Employee>(null);
Why?

2021-09-17 14:11 UTC, nantonov commented on TSP/BLL/Services/GenericServiceSetId.cs
> +        public virtual T SetId(int id, T model)
[WTF part] What does this method do?

2021-09-17 14:11 UTC, nantonov commented on TSP/TSP.API/Validators/EmployeeViewModelValidator.cs
> +    public class EmployeeViewModelValidator : AbstractValidator<EmployeeViewModel>
For what you validate this vm?

2021-09-17 14:11 UTC, nantonov commented on TSP/BLL/Services/SetOfficeId.cs
> +    public class SetOfficeId : GenericServiceSetId<Office>, IOfficeSetId
Strange name

2021-09-17 14:11 UTC, nantonov commented on TSP/BLL/Services/SetEmployeeId.cs
> +    public class SetEmployeeId : GenericServiceSetId<Employee>, IEmployeeSetId
Strange name

2021-09-17 14:11 UTC, nantonov commented on TSP/BLL/Services/GenericService.cs
> +        public virtual async Task<T> UpdateAsync(T entity)
Why it virtual?

2021-09-17 15:43 UTC, Blackolf931 commented on TSP/BLL/Services/GenericService.cs
> +        public virtual async Task<T> UpdateAsync(T entity)
fix

2021-09-17 15:43 UTC, Blackolf931 commented on TSP/BLL/Services/SetEmployeeId.cs
> +    public class SetEmployeeId : GenericServiceSetId<Employee>, IEmployeeSetId
deleted

2021-09-17 15:43 UTC, Blackolf931 commented on TSP/BLL/Services/SetOfficeId.cs
> +    public class SetOfficeId : GenericServiceSetId<Office>, IOfficeSetId
deleted

2021-09-17 16:05 UTC, Blackolf931 commented on TSP/TSP.API/Validators/EmployeeViewModelValidator.cs
> +    public class EmployeeViewModelValidator : AbstractValidator<EmployeeViewModel>
fix

2021-09-17 16:05 UTC, Blackolf931 commented on TSP/BLL/Services/GenericServiceSetId.cs
> +        public virtual T SetId(int id, T model)
deleted

2021-09-17 16:05 UTC, Blackolf931 commented on TSP/BLL/Services/EmployeeService.cs
> +                return _mapper.Map<Employee>(null);
fix

2021-09-20 13:49 UTC, nantonov requested changes

2021-09-20 13:49 UTC, nantonov commented on TSP/BLL/Services/IEmployeeRepository.cs
> +    internal interface IEmployeeRepository<T>
empty employee generic repo in BLL?

2021-09-20 13:49 UTC, nantonov commented on TSP/DAL/DI/DependencyDalRegistrar.cs
> +            services.AddScoped<IOfficeRepository, OfficeRepository>(); ;
;

2021-09-20 13:49 UTC, nantonov commented on TSP/TSP.API/Validators/ViewModelAddOfficeValidator.cs
> +         //   RuleFor(x => x.Name).NotEmpty().Matches("^[A-Z][a-zA-Z]*$").WithMessage("Name can't be empty").MaximumLength(60).MinimumLength(3);
Why?

2021-09-20 13:49 UTC, nantonov commented on TSP/TSP.API/ViewModels/EmployeeAddViewModel.cs
> +    public class EmployeeAddViewModel : IHasIdBase
You cannot insert Id

2021-09-20 13:49 UTC, nantonov commented on TSP/TSP.API/ViewModels/OfficeAddViewModel.cs
> +    public class OfficeAddViewModel : IHasIdBase
You cannot insert Id

2021-09-20 14:32 UTC, Blackolf931 commented on TSP/BLL/Services/IEmployeeRepository.cs
> +    internal interface IEmployeeRepository<T>
deleted

2021-09-20 14:32 UTC, Blackolf931 commented on TSP/DAL/DI/DependencyDalRegistrar.cs
> +            services.AddScoped<IOfficeRepository, OfficeRepository>(); ;
fix

2021-09-20 14:32 UTC, Blackolf931 commented on TSP/TSP.API/Validators/ViewModelAddOfficeValidator.cs
> +         //   RuleFor(x => x.Name).NotEmpty().Matches("^[A-Z][a-zA-Z]*$").WithMessage("Name can't be empty").MaximumLength(60).MinimumLength(3);
fix

2021-09-20 14:32 UTC, Blackolf931 commented on TSP/TSP.API/ViewModels/EmployeeAddViewModel.cs
> +    public class EmployeeAddViewModel : IHasIdBase
fix

2021-09-20 14:32 UTC, Blackolf931 commented on TSP/TSP.API/ViewModels/OfficeAddViewModel.cs
> +    public class OfficeAddViewModel : IHasIdBase
fix

2021-09-20 14:36 UTC, nantonov requested changes

2021-09-20 14:36 UTC, nantonov commented on TSP/TSP.API/Controllers/GenericController.cs
> +            viewModel.Id = id;
You can set Id to Model, not ViewModel

2021-09-20 14:36 UTC, nantonov commented on TSP/TSP.API/Validators/ViewModelAddEmployeeValidator.cs
> +    public class ViewModelAddEmployeeValidator : AbstractValidator<EmployeeAddViewModel>
What happened with naming?

2021-09-20 14:36 UTC, nantonov commented on TSP/TSP.API/Validators/ViewModelUpdateEmployeeValidator.cs
> +    public class ViewModelUpdateEmployeeValidator : AbstractValidator<EmployeeUpdateViewModel>
Naming

2021-09-20 14:36 UTC, nantonov commented on TSP/TSP.API/ViewModels/EmployeeAddViewModel.cs
> +        public int Id { get; set; }
We cannot add entity with id

2021-09-20 14:36 UTC, nantonov commented on TSP/TSP.API/ViewModels/EmployeeUpdateViewModel.cs
> +        public int Id { get; set; }
User send the Id in the query

2021-09-20 14:36 UTC, nantonov commented on TSP/TSP.API/ViewModels/OfficeAddViewModel.cs
> +        public int Id { get; set; }
the same

2021-09-20 14:36 UTC, nantonov commented on TSP/TSP.API/ViewModels/OfficeUpdateViewModel.cs
> +        public int Id { get; set; }
will be send through query

2021-09-20 14:56 UTC, Blackolf931 commented on TSP/TSP.API/Controllers/GenericController.cs
> +            viewModel.Id = id;
fix

2021-09-20 14:57 UTC, Blackolf931 commented on TSP/TSP.API/Validators/ViewModelAddEmployeeValidator.cs
> +    public class ViewModelAddEmployeeValidator : AbstractValidator<EmployeeAddViewModel>
fix

2021-09-20 14:57 UTC, Blackolf931 commented on TSP/TSP.API/Validators/ViewModelUpdateEmployeeValidator.cs
> +    public class ViewModelUpdateEmployeeValidator : AbstractValidator<EmployeeUpdateViewModel>
fix

2021-09-20 14:57 UTC, Blackolf931 commented on TSP/TSP.API/ViewModels/EmployeeAddViewModel.cs
> +        public int Id { get; set; }
fix

2021-09-20 14:57 UTC, Blackolf931 commented on TSP/TSP.API/ViewModels/EmployeeUpdateViewModel.cs
> +        public int Id { get; set; }
fix

2021-09-20 14:57 UTC, Blackolf931 commented on TSP/TSP.API/ViewModels/OfficeAddViewModel.cs
> +        public int Id { get; set; }
fix

2021-09-20 14:57 UTC, Blackolf931 commented on TSP/TSP.API/ViewModels/OfficeUpdateViewModel.cs
> +        public int Id { get; set; }
fix

2021-09-20 14:58 UTC, nantonov approved these changes

2021-09-20 17:12 UTC, merged